input {
  tcp {
    port => 5000
    codec => json_lines
  }
}

filter {
  grok {
    match => {
      "log" => "%{TIMESTAMP_ISO8601:event_time} %{LOGLEVEL:log_level} sensor_id=%{DATA:sensor_id} metric=%{DATA:metric_name} value=%{NUMBER:metric_value:float} unit=%{DATA:unit} status=%{DATA:status} message=\"%{DATA:message}\""
    }
    tag_on_failure => ["_sensor_text_grok_failure"]
  }

  mutate {
    replace => {
      "source_type" => "text"
      "pipeline_stage" => "bronze"
    }
    uppercase => ["log_level"]
  }

  date {
    match => ["event_time", "ISO8601"]
    target => "@timestamp"
  }
}

output {
  kafka {
    bootstrap_servers => "kafka:9092"
    topic_id => "sensor-text-logs"
    codec => json
  }

  stdout {
    codec => rubydebug
  }
}
